# Generated by Django 5.1.3 on 2024-11-20 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_passwordhistory_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='PasswordHistory',
        ),
    ]
