# Generated by Django 5.1.3 on 2024-11-22 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customer_id_alter_customer_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.TextField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to='accounts.customer')),
            ],
        ),
    ]
