# Generated by Django 5.1.3 on 2024-11-22 07:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_password_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='password_history',
            name='date_changed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
