# Generated by Django 5.1.3 on 2024-11-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_password_history_date_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='salt',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
