# Generated by Django 5.1.3 on 2024-12-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customer_salt'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.TextField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('salt', models.TextField()),
            ],
        ),
    ]
