# Generated by Django 5.1.3 on 2024-12-03 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password_history',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to='accounts.user'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
