# Generated by Django 5.1.3 on 2024-12-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_customer_name_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='password_history',
            name='salt',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
