# Generated by Django 5.1.3 on 2024-12-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_password_history_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password_history',
            name='id',
        ),
        migrations.AlterField(
            model_name='password_history',
            name='username',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
