# Generated by Django 5.1.3 on 2024-12-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_password_history_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='password_history',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='password_history',
            name='username',
            field=models.TextField(),
        ),
    ]
