# Generated by Django 5.1.3 on 2024-12-08 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_screen', '0002_remove_customer_id_alter_customer_id_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
